src/Entity/Language.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LanguageRepository")
 */
class Language
{
    public function __construct()
    {
        $this->keywords = new ArrayCollection();
    }

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=2, nullable=true)
     */
    private $iso639_1;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nameEnglish;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $namePolish;

    /**
     * @var Collection
     * @ORM\ManyToMany(targetEntity=Keyword::class, cascade={"persist"})
     */
    private $keywords;

    /**
     * @ORM\OneToMany(targetEntity=Sentence::class,mappedBy="language")
     */
    private $sentences;

    public function getId()
    {
        return $this->id;
    }

    public function getIso6391(): ?string
    {
        return $this->iso639_1;
    }

    public function setIso6391(?string $iso639_1): self
    {
        $this->iso639_1 = $iso639_1;

        return $this;
    }

    public function getNameEnglish(): ?string
    {
        return $this->nameEnglish;
    }

    public function setNameEnglish(string $nameEnglish): self
    {
        $this->nameEnglish = $nameEnglish;

        return $this;
    }

    /**
     * @return Keyword[] | Collection
     */
    public function getKeywords()
    {
        return $this->keywords;
    }

    public function setKeywords($keywords): self
    {
        $this->keywords = $keywords;
        return $this;
    }

    public function attachKeyword(Keyword $keywords): self
    {
        $this->keywords->add($keywords);
        return $this;
    }

    /**
     * @return Sentence[]|ArrayCollection
     */
    public function getSentences()
    {
        return $this->sentences;
    }

    /**
     * @param ArrayCollection|Sentence[] $sentences
     */
    public function setSentences($sentences): void
    {
        $this->sentences = $sentences;
    }

    /**
     * @return mixed
     */
    public function getNamePolish()
    {
        return $this->namePolish;
    }

    /**
     * @param mixed $namePolish
     */
    public function setNamePolish($namePolish): void
    {
        $this->namePolish = $namePolish;
    }
}

src/Controller/DashboardController.php
<?php

namespace App\Controller;

use App\Entity\Settings;
use App\Form\Data\Predict;
use App\Form\PredictType;
use App\Form\SettingsType;
use App\Repository\LanguageRepository;

use App\Repository\SettingsRepository;
use App\Service\MachineLearning\LanguagePredictor;
use App\Service\MachineLearning\LanguagePredictValidator;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;


class DashboardController extends Controller
{
    /**
     * @var LanguageRepository
     */
    private $languageRepository;

    /**
     * @var LanguagePredictor
     */
    private $languagePredictor;
    /**
     * @var SettingsRepository
     */
    private $settingsRepository;

    public function __construct(
        LanguageRepository $languageRepository,
        SettingsRepository $settingsRepository,
        LanguagePredictor $languagePredictor
    ) {
        $this->languageRepository = $languageRepository;
        $this->languagePredictor = $languagePredictor;
        $this->settingsRepository = $settingsRepository;
    }

    /**
     * @Route("/", name="dashboard")
     * @param Request $request
     * @param string $appEnv
     * @return Response
     */
    public function index(Request $request, string $appEnv): Response
    {
        $languages = $this->languageRepository->findAll();
        $settings = $this->settingsRepository->getFirstSetting();

        $predictModel = new Predict();
        $formPredict = $this->createForm(PredictType::class, $predictModel);
        $formPredict->handleRequest($request);

        $predicted = null;

        if ($formPredict->isSubmitted() && $formPredict->isValid()) {
            $predicted = $this->languagePredictor->predict($predictModel->getContent());
        }

        $xdebug =  extension_loaded('xdebug');
        $sfEnv = $appEnv;


        return $this->render('dashboard/index.html.twig', [
            'languages' => $languages,
            'formPredict' => $formPredict->createView(),
            'predicted' => $predicted,
            'settings' => $settings,
            'cache' => [file_exists(LanguagePredictor::CACHE_ESTIMATOR), file_exists(LanguagePredictor::CACHE_DATASET)],
            'xdebug' => $xdebug,
            'sfEnv' => $sfEnv,
        ]);
    }
}

templates/dashboard/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dashboard{% endblock %}

{% block body %}
    <div class="row" style="margin-top: 1em">
        <div class="col-sm">
            <div class="card" style="width: 25rem;">
                <div class="card-header">
                    Słowniki
                </div>
                <ul class="list-group list-group-flush">
                    {% for language in languages %}
                        <li class="list-group-item">{{ language.namePolish }} ({{ language.iso6391 }}): {{ language.sentences|length }}
                           zdań
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="col-sm">
            <h3>Predykcja</h3>
            {{ form_start(formPredict) }}
            {{ form_widget(formPredict) }}

            <ul>
                <li>Estymator: {{ settings.estimatorType }}</li>
                <li>Liczba wybranych zdań z każdego języka do nauki: {{ settings.maxDictionarySize }}</li>
                <li>Cache modelu w pliku: {{ settings.saveAndReuseSavedModel ? 'tak' : 'nie' }}</li>
                <li>Cache estymatora {{ cache[0] ? 'tak' : 'nie' }}</li>
                <li>Cache bazy zdan {{ cache[1] ? 'tak' : 'nie' }}</li>
                <li>Xdebug: {{ xdebug ? 'tak' : 'nie' }}</li>
                <li>Symfony env: {{ sfEnv }}</li>
            </ul>
            <input type="submit" class="btn btn-primary" value="Rozpoznaj język"/>
            {{ form_end(formPredict) }}

            {% if(predicted) %}
                <hr>

                <div class="alert alert-success ">
                    Predykcja:
                    {{ predicted }}
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}